CREATE TABLE `questions` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`genre` text NOT NULL,
	`voice_count` integer NOT NULL,
	`clefs` text NOT NULL,
	`key_signature` text NOT NULL,
	`bwv` text NOT NULL,
	`measures` text NOT NULL,
	`duration` real NOT NULL,
	`bpm` integer NOT NULL,
	`source` text NOT NULL,
	`source_label` text NOT NULL,
	`analysis` text NOT NULL,
	`license_note` text NOT NULL,
	`voices` text NOT NULL,
	`enabled` integer DEFAULT true NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
